spring.application.name=techmind

# URL atualizada com a sua PDB local
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
# Usando o usuário dedicado que criamos
spring.datasource.username=SYSTEM
spring.datasource.password= Senha123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect.oracle.prefer_long_raw=true

# Logging: reduzir verbosidade
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.com.zaxxer.hikari=INFO
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF